config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :locations, only: [:index, :new, :create, :show]
  # Defines the root path route ("/")
  root "locations#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/forecast.rb
# frozen_string_literal: true

# This class sends an API request to get the weather based on the locations latitude and longitude
class Forecast
  require 'uri'
  require 'net/http'
	require 'json'

	LOGGER = ActiveSupport::Logger.new(STDOUT)

	attr_reader :response
	attr_accessor :location, :fields, :start_time, :end_time, :timesteps, :units, :timezone

	def initialize(location=nil, fields='weatherCode', start_time=Time.now.utc.iso8601, end_time=(Time.now + 1.day).utc.iso8601, timesteps='current', units='metric', timezone='UTC')
		@location = location
		@fields = fields
		@start_time = start_time
		@end_time = end_time
		@timesteps = timesteps
    @units = units
    @timezone = timezone
		@response = []
	end

	def self.request(location)
		url = URI("https://api.tomorrow.io/v4/timelines")
		api_key = Rails.application.credentials[:tomorrow_io][:api_key]

		# instantiate a new object with the Locations formatted address
		req = Forecast.new(location.coordinates)

		https = Net::HTTP.new(url.host, url.port)
		https.use_ssl = true

		request = Net::HTTP::Get.new("#{url}/?location=#{req.location}&fields=#{req.fields}&startTime=#{req.start_time}&endTime=#{req.end_time}&timesteps=#{req.timesteps}&units=#{req.units}&timezone=#{req.timezone}&apikey=#{api_key}")

		response = https.request(request)

		puts "Response #{response.code} #{response.code.class}"
		if response.code == '200'
			data = JSON.parse(response.body)
      puts "DATA: #{data}"
      forecast = weather_code(data)
		else
			"There was an issue with this request. Error: #{response.code}, #{response.message}"
		end
	end

  def self.weather_code(data)
    return nil if data.nil?

    data['data']['timelines'].first['intervals'].first['values']['weatherCode']
  end
end

app/models/geocode.rb
# frozen_string_literal: true

# This class sends an API request based on the address string in Location to retrieve the latitude and longitude coordinates for Forecast
class Geocode
  require 'uri'
  require 'net/http'
	require 'json'

	LOGGER = ActiveSupport::Logger.new(STDOUT)

	attr_reader :response
	attr_accessor :text, :type, :lang, :limit

	def initialize(text, type='street', lang='en', limit=1)
		@text = text
		@type = type
		@lang = lang
		@limit = limit
		@response = []
	end

	def self.request(location)
		url = URI("https://api.geoapify.com/v1/geocode/search")
		api_key = Rails.application.credentials[:geoapify][:api_key]
		
		# instantiate a new object with the Locations formatted address
		req = Geocode.new(location.format_address(location.address))

		https = Net::HTTP.new(url.host, url.port)
		https.use_ssl = true

		request = Net::HTTP::Get.new("#{url}/?apiKey=#{api_key}&text=#{req.text}&type=#{req.type}&lang=#{req.lang}&limit=#{req.limit}&format=json")

		response = https.request(request)
	
		puts "Response #{response.code} #{response.code.class}"
		if response.code == '200'
			data = JSON.parse(response.body)
			lat = latitude(data)
			lon = longitude(data)
			[lat, lon]
		else
			"There was an issue with this request. Error: #{response.code}, #{response.message}"
		end
	end

	def self.latitude(data)
		return nil if data.nil?

		data['results'].first['lat']
	end

	def self.longitude(data)
		return nil if data.nil?

		lon = data['results'].first['lon']
	end
end

app/models/location.rb
class Location < ApplicationRecord
	validates :address, 		presence: true
	validates :latitude, 		presence: true
	validates :longitude, 	presence: true

	def format_address(address)
		self.address.gsub(/[', ']/, ',' => '%2C', ' ' => '%20')
	end

	# get latitude and longitude
	def coordinates
		lat = self.latitude
		lon = self.longitude
		[lat, lon].join(', ')
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
	before_action :set_location, only: [:show, :update]
  
	def index
		@location = Location.last
		@forecast = Forecast.request(@location)
		puts "Forecast: #{@forecast}"
	end

	def show
	end

	def new
		@location = Location.new
	end

	def create
		@location = Location.new(location_params)
		coordinates = Geocode.request(@location)

		@location.update(location_params.merge(latitude: coordinates.first, longitude: coordinates.last))
		if @location.save
			puts "Location has been saved! #{@location.inspect}"
			respond_to do |format|
				format.html { redirect_to locations_path, notice: "What's the weather is like today?" }
				format.turbo_stream
			end
		# else
		# 	render :new, status: :unprocessable_entity
		end
  end

	def update
		if @location.update(location_params)
      redirect_to locations_path, notice: "location was successfully updated."
    else
      render :edit
    end
	end

	private

		def set_location
			@location = Location.find(params[:id])
		end

		def location_params
			params.require(:location).permit(:name, :address, :latitude, :longitude)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimpleForecast</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/locations/_form.html.slim
= simple_form_for location do |f|
  - if location.errors.any?
    = f.error_notification
  = f.input :name, label: 'Name', error: @location.errors[:name]
  = f.input :address, required: true, label: 'Enter street address', input_html: { autofocus: true }, error: @location.errors[:address]
  = f.submit 'Get Forecast', class: 'btn btn-warning'

app/views/locations/_location.html.slim
h3 Current Forecast
p Location Address #{@location.address}
p Location Coordinates #{@location.latitude}, #{@location.longitude}
p Forecast #{@forecast}

app/views/locations/create.turbo_stream.erb
<%= turbo_stream.replace "locations", @location %>
<%= turbo_stream.update Location.new, "" %>

app/views/locations/index.html.slim
.container
  .header
    h1 Simple Forecast
    = link_to "Search a location", new_location_path, class: "btn btn--primary", data: { turbo_frame: dom_id(Location.new) }

  = turbo_frame_tag Location.new
	= turbo_frame_tag "locations"
  	= render @location
  
  .footer
    small Powered by <a href='https://www.tomorrow.io/'>Tomorrow.io</a>

app/views/locations/new.html.slim
.container
  = link_to sanitize("&larr; Back to Locations"), locations_path

  = turbo_frame_tag @location
    = render "form", location: @location

app/views/locations/show.html.slim
= link_to 'Home', locations_url, class: 'btn btn-primary'